//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimationKamlaV1.Models
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel;
  using System.Web;

  public partial class tbl_home
    {
        public int id { get; set; }
        [DisplayName("Upload Image")]
        public string ImagePath { get; set; }
        public string Short_headline { get; set; }
        public string CreateByWhom { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
  }
}
