//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimationKamlaV1.Models
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel;
  using System.Web;
  using System.Web.Mvc;

  public partial class tbl_category_sub
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> rating { get; set; }
        [DisplayName("Upload Image")]
        public string ImagePath { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string categoryname { get; set; }
        public IEnumerable<SelectListItem> PostCategory { get; set; }
        public tbl_category category { get; set; }
       // public virtual tbl_category category { get; set; }
       
        public HttpPostedFileBase ImageFile { get; set; }
  }
}

